version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    groups:
      all-go-mod-patch-and-minor:
        patterns: [ "*" ]
        update-types: [ "patch", "minor" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
