apiVersion: v1
kind: Service
metadata:
  labels:
    app: traefik-forward-auth
  name: traefik-forward-auth
  namespace: traefik
spec:
  ports:
  - name: auth-http
    port: 4181
    protocol: TCP
    targetPort: 4181
  selector:
    app: traefik-forward-auth
  sessionAffinity: None
  type: ClusterIP
